repos:
  - repo: https://github.com/golangci/golangci-lint
    rev: v2.2.1 # Use the latest golangci-lint version
    hooks:
      - id: golangci-lint
        args: [ --config=.golangci.yml ] # Assuming your config file is named .golangci.yml
